version: "2.0"
services:
  store:
    image: devrd/dockerexp:store
    ports:
      - "8080:8080"
    networks:
      - store-network
    
    depends_on:
      - mariadb
 
  mariadb:
    image: mariadb:10.3
    ports:
      - "3306:3306"
    networks:
      - store-network
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=root  
      - bind-address = 0.0.0.0

networks:
  store-network:
